### PR TITLE
fix build swift build --swift-sdk x86_64-swift-linux-musl -c releas

### PR DESCRIPTION
**Pull request by doozMen**
Followed instructions https://www.swift.org/documentation/articles/static-linux-getting-started.html

### CODE REVIEW

**Review by thebarndog — APPROVED** [review]
Looks good, thanks for the contribution!

**Comment by thebarndog** [comment]
@doozMen feel free to merge whenever

**Comment by doozMen** [comment]
Screenshot 2024-10-21 at 11 03 48

I would love to merge but have rightfully so no rights :). So could you do it. This fix works for us in production some time now so I think it is good to go.

**Comment by thebarndog** [comment]
Merged!

**Pull request merged**
